config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users, only: [:index, :show] do
    collection do
      post "search"
      post "mentor_search"
    end
    resources :chatrooms, only: :create
  end
  post "/users/:id", to: "users#favorite", as: "user_favorite"
  patch "/users/:id", to: "users#unfavorite", as: "user_unfavorite"

  get "/mentors", to: "users#mentors"
  get "/dashboard", to: "pages#dashboard"
  get "/pages", to: "pages#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch::Model
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :messages, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :chatrooms, ->(user) { unscope(where: :user_id).where("chatrooms.user_a_id = :id OR chatrooms.user_b_id = :id", id: user.id) }, class_name: 'Chatroom', dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  acts_as_taggable_on :competences, :languages, :mentor_skills
  acts_as_favoritable
  acts_as_favoritor
  pg_search_scope :search_by_competences_and_users,
                  against: [:first_name,:title,:last_name],
                  using: {
                    tsearch: { prefix: true }
                  },
                  associated_against: {
                    projects: [:title, :description],
                    base_tags: [:name]
                  }

  LANGUAGES = ["French", "German", "Italian", "English", "Greek", "Russian", "Portuguese"]

  COUNTRIES = User.all.map(&:country).uniq


  def chatroom_with(another_user)
    Chatroom.where(user_a: self, user_b: another_user).or(Chatroom.where(user_b: self, user_a: another_user)).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @favorited = current_user.all_favorited
    @competences = ActsAsTaggableOn::Tag.for_context(:competences).map{ |tag| tag.name }
    @users = User.all
    @users = @users.search_by_competences_and_users(params[:choices]) if params[:choices].present?
    @users = @users.tagged_with(params[:languages], :on => :languages, :any => true) if params[:languages].present?
    @users = @users.tagged_with(params[:competences], :on =>:competences, :any => true) if params[:competences].present?
    @users = @users.where(country: params[:countries]) if params[:countries].present?
    @mentors = @users.where(mentor: true)
  end

  def mentors
    @favorited = current_user.all_favorited
    @users = User.where(mentor: true)
    @mentor = true
    @mentor_skills = ActsAsTaggableOn::Tag.for_context(:mentor_skills).map{ |tag| tag.name }
    @search_collection = Project::MISSIONS + @mentor_skills
    @users = @users.search_by_competences_and_users(params[:choices]) if params[:choices].present?
    @users = @users.tagged_with(params[:languages], :on => :languages, :any => true) if params[:languages].present?
    @users = @users.tagged_with(params[:competences], :on =>:competences, :any => true) if params[:competences].present?
    @users = @users.where(country: params[:countries]) if params[:countries].present?
    @mentors = @users.where(mentor: true)
  end

  def search
    @favorited = current_user.all_favorited
    @competences = ActsAsTaggableOn::Tag.for_context(:competences).map{ |tag| tag.name }
    @mentor_skills = ActsAsTaggableOn::Tag.for_context(:mentor_skills).map{ |tag| tag.name }
    @users = params[:page] == "mentors" ? User.where(mentor: true) : User.all
    @mentor = (params[:page] == "mentors")
    @skills = @mentor ? @mentor_skills : @competences
    @users = @users.search_by_competences_and_users(params[:choices]) if params[:choices].present?
    @users = @users.tagged_with(params[:languages], :on => :languages, :any => true) if params[:languages].present?
    @users = @users.tagged_with(params[:competences], :on =>:competences, :any => true) if params[:competences].present?
    @users = @users.where(country: params[:countries]) if params[:countries].present?
    @mentors = @users.where(mentor: true)
    respond_to do |format|
      format.json
    end
  end

  def show
    @user = User.new
    @user = User.find(params[:id])
    @user_projects = Project.where(user_id: @user.id)
    @favorited = current_user.all_favorited
    @chatroom = current_user.chatroom_with(@user)
    if @chatroom.nil?
      user_a_id = current_user.id
      user_b_id = @user.id
      @chatroom = Chatroom.new(user_a_id: user_a_id, user_b_id: user_b_id)
      @chatroom.save
    end
  end

  def favorite
    @user = User.find(params[:id])
    @current_user = current_user
    @current_user.favorite(@user)
    redirect_to dashboard_path
  end

  def unfavorite
    @user = User.find(params[:id])
    @current_user = current_user
    @current_user.unfavorite(@user)
    redirect_to user_path(@user)
  end


  def mentor_search
    @favorited = current_user.all_favorited
    @users = User.where(mentor: true)
    @mentor_skills = ActsAsTaggableOn::Tag.for_context(:mentor_skills).map{ |tag| tag.name }
    @search_collection = Project::MISSIONS + @mentor_skills
    @users = @users.search_by_competences_and_users(params[:choices]) if params[:choices].present?
    @users = @users.tagged_with(params[:languages], :on => :languages, :any => true) if params[:languages].present?
    @users = @users.tagged_with(params[:competences], :on =>:competences, :any => true) if params[:competences].present?
    @users = @users.where(country: params[:countries]) if params[:countries].present?
    @mentors = @users.where(mentor: true)
    respond_to do |format|
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/views/users/_user_index.html.erb
<div class="mx-5" data-controller="uptade-list">
  <div data-uptade-list-target="users">
    <%= render "users_list", users:users, mentor: mentor, skills: skills %>
  </div>
</div>

app/views/users/_users_list.html.erb
<div class ="form">
  <h3 class="my-9" class="my-5">Find a <%= mentor ? "mentor" : "profile" %></h3>
  <p><%= users.count %> <%= (mentor ? "mentor" : "profile").pluralize(users.count) %></p>
  <%= form_with  url: users_path, method: :get, class: "d-flex row search-form me-0", data:{ uptade_list_target:"form",
          action: "change->uptade-list#send"} do %>
    <%= hidden_field_tag :page, action_name %>
    <div class="col-5 pe-0">
      <%= select_tag :choices, options_for_select(skills, params[:choices]), multiple: true, data: {controller: "autocomplete"} %>
    </div>

    <div class="col-3 pe-0">
      <%= select_tag :languages, options_for_select(User::LANGUAGES.sort, params[:languages]), prompt: "Languages", class: "form-select"  %>
    </div>

    <div class="col-3">
      <%= select_tag :countries , options_for_select(User::COUNTRIES.sort, params[:countries]), prompt: "Countries",class: "form-select" %>
    </div>
    <%= button_tag class: "btn-btn-primary col-1"  do  %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
</div>

<div class="user-cards-container">
  <% users.each do |user| %>
    <% next if user == current_user %>
    <%= link_to user_path(user) do %>
      <div class="user-card mt-4">
        <div class="user-card-img-container">
          <%= cl_image_tag user.photo.key, width: 500, height: 500, class: "user-card-image", crop: :thumb, gravity: :face %>
          <% if user.mentor == true %>
            <i class="fa-solid card-graduation fa-graduation-cap"></i>
          <% end %>
        </div>
        <div class="user-card-content">
          <h3><%= user.first_name %> <%= user.last_name%>
          </h3>
          <p><%= user.title %></p>
          <p class="batch-badge">Batch #<strong><%= user.batch_number %></strong></p>
          <div class="skill-badges">
            <% user.competence_list.first(3).each do |competence| %>
              <span class="badge"><%= competence %></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render "user_index", mentor: false, skills: @competences, users: @users %>

app/views/users/mentors.html.erb
<%= render "user_index", mentor: true, skills: @mentor_skills, users: @users %>

app/views/users/show.html.erb
<div class="card-container-profile">

  <div class="container-photo-title">
      <%= cl_image_tag @user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: "user-photo" %>
      <div class="name-city">
        <h2 class="highlight-name"><%= @user.first_name %> <%= @user.last_name %></h2>
        <p><%= @user.city %> - <%= @user.country %></p>
        <p>Fluent in <% @user.languages.each do |l| %><%= l %><% if l == @user.languages.last %><%= "." %><% else %><%=", "%><% end %>
        <% end %>
        </p>

      <p><i class="fa-solid fa-lightbulb"></i> She was part of the batch #<strong><%= @user.batch_number %></strong> in <%= @user.graduation_year %></p>

      </div>
      <div class="cta">
      <% if @chatroom %>
        <div class="offcanvas offcanvas-end modal-chatroom" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Chat with <%= @user.first_name %></h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <%= render "chatrooms/chatroom", chatroom: @chatroom %>
          </div>
        </div>
        <%= button_tag class: "btn-red-profile", data: {bs_toggle: "offcanvas", bs_target: "#offcanvasRight"} do %>
          <i class="fa-regular fa-comments"></i> Chat with <%= @user.first_name %>
        <% end %>
      <% else %>
        <%= link_to user_chatrooms_path(@user), data: { turbo_method: :post }, class: "btn-red-profile" do %>
          <i class="fa-regular fa-comments"></i> Chat with <%= @user.first_name %>
        <% end %>
      <% end %>

      <% if @user.favorited_by?(current_user) %>
        <p><i class="fa-solid card-graduation-unfavorited fa-graduation-cap"></i><%= @user.first_name %> is your mentor</p>
      <% else %>
        <%= link_to user_favorite_path(@user) do %>
         <i class="fa-solid card-graduation fa-graduation-cap"></i><%= link_to 'Add as a mentor', user_favorite_path(@user), class: "add-mentor", data: { turbo_method: :post, controller: "notation" } %>
        <br>
          <% end %>
      <% end %>
     </div>
    </div>

  <div class="card-profile">
    <div class="card-profile-infos">
      <h3><%= @user.first_name %> is a <%= @user.title %></h3>
      <ul class="tags">
        <% @user.competence_list.each do |skill| %>
        <li class="tag-list"><%= skill %></li>
          <% end %>
      </ul>
      <p><%= @user.description %></p>
    </div>
    </div>
  </div>

<div class="card-profile">
    <h3><%= @user.first_name %>'s offers:</h3>
      <% if @user_projects.exists? %>
        <%= render "projects/show", chatroom: @chatroom  %>
      <% else %>
        <%= "No offers yet..."  %>
      <% end %>

 <%= render "shared/mentors" if @user.mentor == true %>
  </ul>
  </div>

</div>