config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users, only: [:index, :show] do
    collection do
      post "search"
      post "mentor_search"
    end
    resources :chatrooms, only: :create
  end
  post "/users/:id", to: "users#favorite", as: "user_favorite"
  patch "/users/:id", to: "users#unfavorite", as: "user_unfavorite"

  get "/mentors", to: "users#mentors"
  get "/dashboard", to: "pages#dashboard"
  get "/pages", to: "pages#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/HBecquembois/wagon-women-worldwide" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://twitter.com/Lewagonparis" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://fr.linkedin.com/in/h%C3%A9l%C3%A8ne-becquembois-66592a118" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="3W-copyright">
    Wagon Women Worldwide®, in memory of Ada Lovelace, made with <i class="fas fa-heart"></i> in partnership with <a href="https://www.lewagon.com/" target="_blank">Le Wagon.</a>
  </div>
</div>

app/views/shared/_mentors.html.erb
 <h3 class="smaller-h3">Her mentoring skills:</h3>
   <ul class="tags">
  <% @user.mentor_skill_list.each do |skill| %>
  <li class="tag-list"><%= skill %></li>
    <% end %>
  </ul>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>">
  <div class="container-fluid">
    <div class="btn general-icon">
      <div class="adaicon", alt="ada lovelace icon"></div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item my-2">
            <%= link_to "All users", users_path, class: "nav-link link" %>
          </li>
          <li class="nav-item my-2">
            <%= link_to "Mentor search", mentors_path, class: "nav-link link" %>
          </li>
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar", alt: "dropdown menu"  %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-site <%= yield(:navbar_class) %>">
  <div class="container-fluid">
    <div class="d-flex">
      <a href="/">
          <div class="btn general-icon">
            <div class="adaicon", alt="ada lovelace icon"></div>
          </div>
      </a>
      <h1 class="title"><div class="indigo">W</div>agon <div class="indigo">W</div>omen <div class="indigo">W</div>orldwide</h1>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <li class="nav-item active my-2">
              <%= link_to "Home", root_path, class: "nav-link link" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "All users", users_path, class: "nav-link link" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to "Mentor search", mentors_path, class: "nav-link link" %>
            </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar", alt: "dropdown menu"  %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <%= cl_image_tag current_user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: "user-side-bar-image" %>
  <div class="sidebar-name">
    <h3><%= current_user.first_name  %></h3>
    <h3><%= current_user.last_name  %></h3>
  </div>
  <ul>
    <li> <i class="fa-solid fa-arrow-right"></i>
    <%= link_to "My dashboard", dashboard_path, class:"#{'active-sidebar' if controller_name == 'pages' && action_name == 'dashboard' && @tab != 'message'}"  %> </li>

    <li> <i class="fa-solid fa-arrow-right"></i>
    <%= link_to "My messages", dashboard_path(tab: 'message'), class:"#{'active-sidebar' if controller_name == 'pages' && action_name == 'dashboard' && @tab == 'message'}" %></li>
    <% if @favorited.present? %>
      <div class="spacer"></div>
        <li><i class="fa-solid fa-graduation-cap"></i> My mentors</li>

            <div class="my-mentors">
            <% @favorited.each do |f| %>

              <li><%= cl_image_tag f.photo.key, width: 25, height: 25, crop: :thumb, gravity: :face, class: "rounded" %>  <%= link_to f.first_name, user_path(f), class:"name" %></li>
                <% end %>
            </div>
    <% end %>
  </ul>
</div>