config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users, only: [:index, :show] do
    collection do
      post "search"
      post "mentor_search"
    end
    resources :chatrooms, only: :create
  end
  post "/users/:id", to: "users#favorite", as: "user_favorite"
  patch "/users/:id", to: "users#unfavorite", as: "user_unfavorite"

  get "/mentors", to: "users#mentors"
  get "/dashboard", to: "pages#dashboard"
  get "/pages", to: "pages#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/dashboard.html.erb
    <div class="container-photo-title-dashboard">
        <div class="name-city-dash">
          <h2 class="welcome">Welcome to your dashboard, <span class="name"><%= @user.first_name %></span>!</h2>
          <p><i class="fa-solid fa-lightbulb"></i> Batch #<strong><%= @user.batch_number %></strong> in <%= @user.graduation_year %></p>
            <% @user.competence_list.each do |skill| %>
              <li class="tag-list"><%= skill %></li>
                <% end %>
          </div>
        <div class="cta">
        </div>
     </div>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' unless @tab == 'message'%>" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">My <%= @user.mentor ? "mentorees" : "mentors" %> (<%= @favorited.count %>)
</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' if @tab == 'offer'%>" id="offer-tab" data-bs-toggle="tab" data-bs-target="#offer" type="button" role="tab" aria-controls="offer" aria-selected="false">My offers (<%= @user_projects.count %>)</button>
  </li>
    <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' if @tab == 'message'%>" id="message-tab" data-bs-toggle="tab" data-bs-target="#message" type="button" role="tab" aria-controls="message" aria-selected="false">My messages (<%= @user_real_chats.count %>)</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade <%='show active' unless @tab == 'message' %>" id="home" role="tabpanel" aria-labelledby="home-tab">
  <div class="d-block m-3">


   <% @favorited.each do |m| %>
    <%= link_to user_path(m.id) do %>
      <div class="card-dashboard">
         <%= cl_image_tag m.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face %>
          <div class="card-dashboard-infos">
            <%= link_to "#{m.first_name} #{m.last_name}", user_path(m.id), class: "mentor-name-card-dash" %>
              <p><%= m.title  %></p>
              <p><i class="fa-solid fa-lightbulb"></i> Batch #<strong><%= m.batch_number %></strong> in <%= m.graduation_year %></p>
          </div>
        <div class="close-icon">
            <%= link_to user_unfavorite_path(m), data: { turbo_method: :patch } do %>
            <i class="fa-solid fa-xmark"></i>
              <% end %>
        </div>
      </div>
       <% end %>
     <% end %>

  </div>
  </div>
    <div class="tab-pane fade <%='show active' if @tab == 'offer'%>" id="offer" role="tabpanel" aria-labelledby="offer-tab">
    <div class="project-nav d-block m-3">
    <% if @user_projects.present? %>
      <div class="card-dashboard-project">
      <ol>
        <% @user_projects.each do |p| %>
          <h5><li><i class="fa-solid fa-computer"></i> <%= p.title %></li></h5>
          <p><%= p.description %></p>
          <% end %>
          <% else %>
          <p class="no-offer"><i class="fa-solid fa-computer"></i> No offer yet...</p>
      <% end %>
      </ol>
      </div>
    </div>
    </div>
    <div class="tab-pane fade <%='show active' if @tab == 'message'%>" id="message" role="tabpanel" aria-labelledby="message-tab">
      <div class="d-block m-3 card-message">
              <div class="d-flex justify-content-around mx-10">
                <div class="logo">
                 <p class="discussion">Messages with mentors & alumni:</p>
                <i class="fa-solid logo-message fa-user-group"></i>
                </div>

        <div class= "list-chat">
                  <% @user_real_chats.each do |c| %>
                    <div class="offcanvas offcanvas-end modal-chatroom" tabindex="-1" id="offcanvasRight<%=c.id%>" aria-labelledby="offcanvasRightLabel">
                      <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasRightLabel"> Chat with <%= c.user_b.first_name %></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                      </div>
                      <div class="offcanvas-body">
                        <%= render "chatrooms/chatroom", chatroom: c %>
                      </div>
                    </div>

                    <button class="btn btn-red-profile m-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight<%=c.id%>" aria-controls="offcanvasRight"> <i class="fa-regular white-bubble fa-comments"></i> <%= c.user_b.first_name %> <%= c.user_b.last_name %></button>
                  <% end %>
                </div>
              </div>
         </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>
<div class="banner">
  <div class="banner-content text-center">

    <h1>Wagon Women Worldwide</h1>
    <h3>Connecting women</h3>
  </div>
</div>


<div class= "display:flex arrow arrow-first"></div>
<div class=" display:flex arrow arrow-second"></div>

<div class="container-fluid p-3">
  <div class="container my-4">
    <h2 class="text-center">Advantages of our mentoring program <i class="fa-solid card-graduation fa-graduation-cap"></i>
    </h2>
    <div class="d-flex justify-content-between" data-aos="fade-up">
      <div class="list">
        <ul>
          <br>
          <li><i class="fa-solid fa-arrow-right fa-beat"></i>  Join a support community of the <a href="https://www.lewagon.com/" target="_blank">Le Wagon</a>'s women!</li>
          <li><i class="fa-solid fa-arrow-right fa-beat"></i>  As a junior, benefit from other women experiences!</li>
          <li><i class="fa-solid fa-arrow-right fa-beat"></i>  As a senior, share your experience or look for a collaborator!</li>
          <li><i class="fa-solid fa-arrow-right fa-beat"></i>  Exchange and chat!</li>
        </ul>
      </div>
      <div class="testimony-card">
        <div class="testimony-card-image">
          <img src="https://kitt.lewagon.com/placeholder/users/lesly75" alt="">
        </div>
        <div class="testimony-card-content">
          <div>
            <h3>Lesly Urie,<p>Junior web developer</p></h3>
          </div>
          <p class="testimony-text"><i class="fa-solid fa-quote-left fa-beat"></i> Thanks to Wagon Women Worldwide, I contacted a mentor looking for a code review. Through her I managed to get a job at Doctolib! <i class="fa-solid fa-quote-right fa-beat"></i></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid bg-lightred p-3">
  <div class="container my-4">
    <h2 class="text-center">Join the program!</h2>
    <div class="d-flex justify-content-between">
      <%= link_to mentors_path, class: 'home-card-link' do %>
        <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("card_home2.jpg") %>)">
          <div class="home-card-btn">
            <span class="btn-card-home">Need a mentor?</span>
          </div>
        </div>
      <% end %>
      <%= link_to dashboard_path, class: 'home-card-link' do %>
        <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("card_home5.jpg") %>)">
          <div class="home-card-btn">
            <span class="btn-card-home">Want to be a mentor?</span>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>